### ISSUE TITLE
Issues based on koolba's comments

### ISSUE THREAD

**Issue by seveibar** [seamapi/prefixed-api-key#1]
_from koolba [via hacker news](https://news.ycombinator.com/reply?id=31334489&goto=item%3Fid%3D31333933%2331334489)_

- [x] You can promisify randomBytes once and reuse it rather than twice for every invocation
- [x] There shouldn’t be a default value for the company name or people will end up using it.
- [ ] The company name isn’t validated so it could contain underscores which would cause issues with the short token parsing as it assumes it’s the second “chunk”
- [ ] The equals comparison of the hashes for the secrets is not timing safe. It’s not as bad as if they were plain text but it does short circuit due to how string equals works. Use the actual built in timing safe equals on the Buffer hash (not the stringified hex).

**Comment by puskuruk** [comment]
I've created a small pr for the 2 issues above. But I think we should improve it. We should give an error when there is no `keyPrefix`. What can be the best approach for giving errors in your use case?

#3

**Comment by seveibar** [comment]
Hey @puskuruk ! Thanks for the PR, a big improvement. `throw new Error("keyPrefix is required")` is good and simple enough for now!
